#!/usr/bin/with-contenv bash

mkdir -p /config/{data}


[[ -L /mFi/data && ! /mFi/data -ef /config/data ]] && unlink /mFi/data


[[ ! -L /mFi/data ]] && ln -s /config/data /mFi/data


chown -R abc:abc /config /mFi
