#!/usr/bin/with-contenv bash

mkdir -p /config/{data}


[[ -L /mfi/data && ! /mfi/data -ef /config/data ]] && unlink /mfi/data


[[ ! -L /mfi/data ]] && ln -s /config/data /mfi/data


chown -R abc:abc /config /mfi
