#!/usr/bin/with-contenv bash

[[ ! -f /config/keystore ]] &&  keytool -genkey -keyalg RSA -alias mfi -keystore /config/keystore -storepass devcontrolenterprise -keypass devcontrolenterprise -validity 1825 -keysize 4096 -dname "cn=mfi"

chown abc:abc /config/keystore
